//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profit
    {
        public int Profit_ID { get; set; }
        public int ProductOrderID { get; set; }
        public decimal ProfitAmount { get; set; }
    
        public virtual OrderProduct OrderProduct { get; set; }
    }
}
