//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TempOrder()
        {
            this.TempOrderProducts = new HashSet<TempOrderProduct>();
        }
    
        public int OrderID { get; set; }
        public System.DateTime date { get; set; }
        public decimal totalAmount { get; set; }
        public string Size { get; set; }
        public int Quantity { get; set; }
        public string PayMentMethod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TempOrderProduct> TempOrderProducts { get; set; }
    }
}
