//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempOrderProduct
    {
        public int ProductOrderID { get; set; }
        public int OrderID { get; set; }
        public int ProductID { get; set; }
        public int CustomerID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ProductHistory ProductHistory { get; set; }
        public virtual TempOrder TempOrder { get; set; }
    }
}
